import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Banner from '../components/Banner'
import ProductFeed from '../components/ProductFeed'

export async function getServerSideProps(){
  const data = await fetch('https://fakestoreapi.com/products')
  .then(res=>res.json())
  return {
    props: {
      data: data,
    },
  }
}
const Home: NextPage = (props) => {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Amazon 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Main */}
      <main className="mx-auto max-w-screen-2xl">
        {/* Banner */}
        <Banner />
        {/* Product Feed */}
        <ProductFeed data={props.data} />
      </main>
    </div>
  )
}

export default Home
